name: workshop
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10 # 3.10 is reuqired by openmm 7.7.0. Igfold relxation using openmm cannot run if openfold is at 8.x versions. 
  - abnumber
  - openmm=7.7.0 # required by igfold if relaxation is used. 
  - pdbfixer
  - pip
  - pip:
      - crewai
      - crewai-tools
      - python-dotenv
      - pandas
      - numpy
      - matplotlib
      - loguru
      - igfold
      - biopython
      - tokenizers<0.21.0 # igfold has this constraint
